---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "iptables.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "iptables.labels" . | indent 4 }}
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "iptables.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "iptables.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: iptables-init
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - custom-add-iptables.sh
          workingDir: /opt/custom-iptables
          volumeMounts:
            - name: custom-iptables-config
              mountPath: /opt/custom-iptables
            - name: iptables-hostpath
              mountPath: /var/lib/iptables
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: iptables-sleep
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sleep
            - infinity
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      hostNetwork: true
      volumes:
        - name: custom-iptables-config
          configMap:
            name: {{ .Values.configmap.name }}
        -  name: iptables-hostpath
           hostPath:
             path: {{ .Values.iptablesHostpath }}
      terminationGracePeriodSeconds: 0
